#!/usr/bin/env python
#
# psynet documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#
import json
import os
import posixpath
import re
import subprocess
import sys
from glob import glob
from io import StringIO
from os.path import abspath, basename, join

import pandas as pd
import polib

import psynet
from psynet.utils import get_language_dict

sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("_ext"))

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",
    "sphinx_autodoc_typehints",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_inline_tabs",  # TODO: remove once we migrate to PyData Sphinx theme
    "sphinx_reredirects",
    "demo_carousel",
    "research_list",
    "lab_note",
    "myst_parser",
    "skill_pages",
]

# Render defaults as written in the source. Defaults computed at import time,
# such as paths into the installed package or the home directory, would
# otherwise show the build machine's paths.
autodoc_preserve_defaults = True

# Old page paths are published and linked externally, so every moved or
# deleted page needs an entry in redirects.json (old docname -> new docname).
with open("redirects.json") as f:
    _redirect_docnames = json.load(f)
redirects = {
    old: posixpath.relpath(new + ".html", posixpath.dirname(old) or ".")
    for old, new in _redirect_docnames.items()
}
# The stub body names the new page for readers that don't follow redirects,
# such as coding agents fetching pages with curl.
redirect_html_template_file = "_templates/redirect.html"


def _check_redirects(app, env):
    """Warn about redirects to missing pages or from pages that still exist."""
    from sphinx.util import logging

    logger = logging.getLogger(__name__)
    for old, new in _redirect_docnames.items():
        if new not in env.found_docs:
            logger.warning(f"redirects.json: target {new!r} (from {old!r}) not found")
        if old in env.found_docs:
            logger.warning(f"redirects.json: {old!r} is still a page; remove it")


_RELEASE_TAG_RE = re.compile(r"^v(\d+\.\d+\.\d+(?:(?:rc|a)\d+)?)$")
_INSTALL_LINE_RE = re.compile(r"^(\s*)uv pip install psynet\s*$", re.MULTILINE)


def _git(*args):
    """Return the output of a Git command run in the PsyNet checkout, or None."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=os.path.dirname(os.path.abspath(__file__)),
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.stdout.strip() or None


def _psynet_install_command():
    """Return the install command for the PsyNet version these docs were built from.

    A release tag installs that release from PyPI; any other commit installs
    that commit from GitLab, so the docs stay valid as later versions appear.
    """
    for tag in (_git("tag", "--points-at", "HEAD") or "").split():
        match = _RELEASE_TAG_RE.match(tag)
        if match:
            return f'uv pip install "psynet=={match.group(1)}"'
    commit = _git("rev-parse", "HEAD")
    if commit:
        return (
            'uv pip install "psynet @ '
            f'git+https://gitlab.com/PsyNetDev/PsyNet@{commit}"'
        )
    return "uv pip install psynet"


psynet_install_command = _psynet_install_command()


def _pin_install_commands(app, docname, source):
    """Rewrite ``uv pip install psynet`` code lines to install this docs version."""
    command = app.config.psynet_install_command
    source[0] = _INSTALL_LINE_RE.sub(lambda match: match.group(1) + command, source[0])


def setup(app):
    app.connect("env-check-consistency", _check_redirects)
    # Rebuild type "env" makes incremental builds reread every page when the
    # command changes; otherwise cached pages keep the previous commit.
    app.add_config_value("psynet_install_command", psynet_install_command, "env")
    app.connect("source-read", _pin_install_commands)


copybutton_prompt_text = r">>> |\.\.\. |\$ |# "
copybutton_prompt_is_regexp = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# Markdown is used only for the Agent Skill pages generated by _ext/skill_pages.py.
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
# Skill files are written for agents and sometimes skip heading levels.
suppress_warnings = ["myst.header"]
myst_heading_anchors = 3

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "PsyNet"
copyright = "2026, Peter Harrison"
author = "Peter Harrison"

# The visible docs version is shown by the theme's version switcher.
version = ""
release = ""

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

linkcheck_ignore = [
    # GitLab answers signed-out automated requests for these with 403 or 404:
    # the public issue list, and pages that need a login or a private repo.
    r"https://gitlab\.com/PsyNetDev/PsyNet/-/issues/?$",
    r"https://gitlab\.com/PsyNetDev/PsyNet/-/releases/new$",
    r"https://gitlab\.com/-/user_settings/personal_access_tokens$",
    r"https://gitlab\.com/computational-audition-lab/psynet-deployment-tests/?$",
    # Local development URLs used in tutorial examples; no server is
    # running during linkcheck.
    r"https?://localhost(:\d+)?(/.*)?$",
    r"https?://127\.0\.0\.1(:\d+)?(/.*)?$",
    # Stable reference page that aggressively rate-limits automated checks.
    r"https://www\.gnu\.org/software/gettext/manual/html_node/Usual-Language-Codes\.html",
    # ColorBlindnessTest media prefix. Listing the prefix is forbidden;
    # the plate files under it (e.g. ishihara-1.jpg) are public.
    r"https://s3\.amazonaws\.com/ishihara-eye-test/jpg/?$",
    # PNAS answers automated requests with 403; the DOI resolves in a browser.
    r"https://doi\.org/10\.1073/pnas\.2420179123$",
    # Citation in format_timedelta; Stack Overflow blocks automated checkers.
    r"https://stackoverflow\.com/questions/538666/format-timedelta-to-string/?$",
    # Official Docutils pages; SourceForge blocks automated checkers.
    r"https://docutils\.sourceforge\.io/docs/user/rst/quickstart\.html$",
    r"https://docutils\.sourceforge\.io/docs/ref/rst/restructuredtext\.html$",
    # MPI Aesthetics pages; the server omits the GEANT intermediate cert.
    r"https://www\.aesthetics\.mpg\.de/en\.html$",
    r"https://www\.aesthetics\.mpg\.de/en/research/research-group-computational-auditory-perception\.html$",
    # Gold-MSI Shiny apps; the server omits the Sectigo intermediate cert.
    r"https://shiny\.gold-msi\.org/gmsiconfigurator/?$",
    r"https://shiny\.gold-msi\.org/gmsi_toplevel/?$",
]

# CI runners occasionally see a healthy host stall past linkcheck_timeout.
# Sphinx only retries checks whose status is "broken", so timeouts have to be
# reported as broken for linkcheck_retries to apply to them. This costs no
# strictness: linkcheck already exits non-zero for timeouts either way.
linkcheck_report_timeouts_as_broken = True
linkcheck_retries = 3

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = "pydata_sphinx_theme"
html_title = "PsyNet documentation"
html_short_title = html_title

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_favicon = "_static/images/psynet.ico"

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    "css/custom.css",
]

html_js_files = [
    "js/custom.js",
]

# Prevent Sphinx from wrapping scaled images in links; this avoids
# theme link styling artifacts around inline title logos.
html_scaled_image_link = False

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "psynetdoc"

# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [
    (master_doc, "psynet.tex", "PsyNet Documentation", "Peter Harrison", "manual"),
]

# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "psynet", "PsyNet Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "psynet",
        "PsyNet Documentation",
        author,
        "psynet",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# This creates an 'Edit in GitLab' button on each documentation page.
# This will take the user to a web IDE where they can propose changes
# to the documentation page.
version_match = os.environ.get(
    "DOCS_VERSION", os.environ.get("CI_COMMIT_TAG", "latest")
)
version_switcher_json_url = os.environ.get(
    "DOCS_VERSION_SWITCHER_JSON", "_static/version_switcher.json"
)

html_theme_options = {
    "github_url": "https://gitlab.com/PsyNetDev/PsyNet/",
    "use_edit_page_button": True,
    "header_links_before_dropdown": 11,
    "footer_start": ["sphinx-version"],
    # Keep page TOC available in the right sidebar as well.
    "secondary_sidebar_items": ["page-toc", "edit-this-page"],
    # Include top-level page sections in section navigation.
    "show_toc_level": 1,
    # Expand more levels in the left navigation tree.
    "show_nav_level": 2,
    # Enable the version selector in the header for multi-version docs.
    "switcher": {
        "json_url": version_switcher_json_url,
        "version_match": version_match,
    },
    "check_switcher": False,
    "navbar_end": ["theme-switcher", "version-switcher", "navbar-icon-links"],
}

html_sidebars = {
    "**": ["search-field", "sidebar-nav-bs"],
    "index": [],
}

html_context = {
    "gitlab_user": "PsyNetDev",
    "gitlab_repo": "PsyNet",
    "gitlab_version": "master",
    "doc_path": "docs",
}

language_dict = get_language_dict("en")
psynet_init_path = abspath(psynet.__file__)


def extract_translation_information():
    locales_dir = join(
        psynet_init_path.replace(basename(psynet_init_path), ""), "locales"
    )
    po_files = glob(locales_dir + "/*/*/*.po")

    results = []
    for po_file in po_files:
        language_iso = po_file.split("/")[-3]
        language_name = language_dict[language_iso]
        po = polib.pofile(po_file)
        total_entries = len(po)
        untranslated_entries = len([entry for entry in po if entry.msgstr == ""])
        unverified_entries = len(
            [entry for entry in po if entry.fuzzy and entry.msgstr != ""]
        )
        results.append(
            {
                "language_iso": language_iso,
                "language_name": language_name,
                "percent_verified": round(
                    (total_entries - unverified_entries) / total_entries * 100, 1
                ),
                "percent_translated": round(
                    (total_entries - untranslated_entries) / total_entries * 100, 1
                ),
                "translator": po.metadata.get("Last-Translator", "Unknown"),
            }
        )

    return pd.DataFrame(results).sort_values("language_name").to_dict("records")


def percent(s):
    return f"{s} %"


def process_row(row):
    language = f"{row['language_name']} (``{row['language_iso']}``)"
    return [
        language,
        percent(row["percent_translated"]),
        percent(row["percent_verified"]),
        row["translator"],
    ]


class RstCloth:
    def __init__(self, output_file):
        self.output_file = output_file

    def title(self, title):
        self.output_file.write(f"""{"=" * len(title)}\n{title}\n{"=" * len(title)}\n""")

    def h3(self, title):
        self.output_file.write(f"""{title}\n{"-" * len(title)}\n""")

    def write_rows(self, rows):
        first = True
        for row in rows:
            if first:
                self.output_file.write(f"""   * - {row}\n""")
                first = False
            else:
                self.output_file.write(f"""     - {row}\n""")

    def table(self, header, rows):
        self.output_file.write(""".. list-table::\n""")
        self.output_file.write("""   :header-rows: 1\n""")
        self.output_file.write("""   :widths: 15 15 15 55\n""")
        self.newline()
        self.write_rows(header)
        for row in rows:
            self.write_rows(row)

    def newline(self):
        self.output_file.write("\n")


def generate_translation_table():
    output = StringIO()
    doc = RstCloth(output)
    doc.title("Translation dashboard")
    doc.newline()

    table = extract_translation_information()
    doc.h3(f"PsyNet is available in {len(table)} languages:")

    doc.table(
        ["Language", "Percent translated", "Percent verified", "Translator"],
        [process_row(row) for row in table],
    )

    output_path = "dashboards/translation.rst"
    content = output.getvalue()
    if not os.path.exists(output_path) or open(output_path).read() != content:
        with open(output_path, "w") as output_file:
            output_file.write(content)


generate_translation_table()
